//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.29 at 04:10:38 PM MSK 
//


package org.satel.eip.project14.adapter.pyramid.domain.command.container;

import java.util.ArrayList;
import java.util.List;

public class ArrayOfGuids {

    protected List<String> guids;

    public List<String> getGuids() {
        if (guids == null) {
            guids = new ArrayList<String>();
        }
        return this.guids;
    }

}
