//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.29 at 04:10:38 PM MSK 
//


package org.satel.eip.project14.adapter.pyramid.domain.command.container;

import lombok.Getter;
import lombok.Setter;

import javax.xml.datatype.XMLGregorianCalendar;

@Getter
@Setter
public class GetMeterRequest {

    protected XMLGregorianCalendar beginDateTime;
    protected XMLGregorianCalendar endDateTime;
    protected Integer offset;
    protected Integer limit;
    protected ArrayOfGuids arrayOfGuids;

}
