//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.29 at 04:10:38 PM MSK 
//


package org.satel.eip.project14.adapter.pyramid.domain.command.container;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;

import java.time.Instant;

@Getter
@Setter
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetMeterRequest {

    @JsonFormat(shape = JsonFormat.Shape.STRING, timezone = "UTC")
    protected Instant beginDateTime;
    @JsonFormat(shape = JsonFormat.Shape.STRING, timezone = "UTC")
    protected Instant endDateTime;
    protected Integer offset;
    protected Integer limit;
    protected ArrayOfGuids arrayOfGuids;

}
